name: Cloud Run Deploy

on:
  push:
    branches:
    - master
    - main
env:
  # Change this section according to your needs
  IMAGE_NAME:   covid-19-image
  SERVICE:      covid-19
  DOMAIN_NAME:  covid-19.demo.community.intersystems.com

  # Leave this section untouched
  PROJECT_ID:   iris-community-demos
  CLUSTER_NAME: demo
  GITHUB_SHA:   ${{ github.sha }}
  GCR_LOCATION: eu.gcr.io
  REGION:       europe-west2
  NAMESPACE:    contest

jobs:
  deploy-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: '327.0.0'
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push image
      run: |
        docker build -t ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA} .
        docker push ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}

    - name: Deploy to Cloud Run
      run: |
        gcloud config set project ${PROJECT_ID}

        gcloud run deploy ${SERVICE}   \
          --platform gke               \
          --cluster ${CLUSTER_NAME}    \
          --cluster-location ${REGION} \
          --namespace ${NAMESPACE}     \
          --port 52773                 \
          --min-instances 1            \
          --memory 512Mi               \
          --timeout 300                \
          --image ${GCR_LOCATION}/${PROJECT_ID}/${IMAGE_NAME}:${GITHUB_SHA}

        if [[ $(gcloud run domain-mappings list --platform gke --cluster ${CLUSTER_NAME} --cluster-location ${REGION} --namespace ${NAMESPACE} --filter "DOMAIN=${DOMAIN_NAME}" | grep -v DOMAIN | wc -l) == 0 ]]; then
          gcloud run domain-mappings create \
            --service ${SERVICE}            \
            --platform gke                  \
            --cluster ${CLUSTER_NAME}       \
            --cluster-location ${REGION}    \
            --namespace ${NAMESPACE}        \
            --domain ${DOMAIN_NAME}
        fi

    - name: Enable TLS-access
      run: |
        gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${REGION} --project ${PROJECT_ID}
        kubectl version
        kubectl patch configmap config-domainmapping -n knative-serving -p '{"data":{"autoTLS":"Enabled"}}'
